### for DSS-Server and Eventchecker APPJOINT
MYSQL_HOST=127.0.0.1
MYSQL_PORT=3306
MYSQL_DB=dss_dev
MYSQL_USER=xxx
MYSQL_PASSWORD=xxx

##hive的配置
HIVE_HOST=127.0.0.1
HIVE_PORT=3306
HIVE_DB=xxx
HIVE_USER=xxx
HIVE_PASSWORD=xxx